package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserManagerService service = new UserManagerService();
 * UserManagerServiceSoap portType = service.getUserManagerServiceSoap();
 * portType.addUser(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserManagerService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://syn.wanfangdata.com.cn/UserManagerService.asmx?wsdl")
public class UserManagerService extends Service {

	private final static URL USERMANAGERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.webservice.UserManagerService.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.webservice.UserManagerService.class.getResource(".");
			url = new URL(baseUrl, "http://syn.wanfangdata.com.cn/UserManagerService.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://syn.wanfangdata.com.cn/UserManagerService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERMANAGERSERVICE_WSDL_LOCATION = url;
	}

	public UserManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserManagerService() {
		super(USERMANAGERSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"UserManagerService"));
	}

	/**
	 * 
	 * @return returns UserManagerServiceSoap
	 */
	@WebEndpoint(name = "UserManagerServiceSoap")
	public UserManagerServiceSoap getUserManagerServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/", "UserManagerServiceSoap"),
				UserManagerServiceSoap.class);
	}

	/**
	 * 
	 * @return returns UserManagerServiceSoap
	 */
	@WebEndpoint(name = "UserManagerServiceSoap12")
	public UserManagerServiceSoap getUserManagerServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "UserManagerServiceSoap12"),
				UserManagerServiceSoap.class);
	}

}
