package com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserManagerServiceSoap", targetNamespace = "http://tempuri.org/")
public interface UserManagerServiceSoap {

	/**
	 * ��Ӹ����û���Ϣ
	 * 
	 * @param user
	 * @return returns int
	 */
	@WebMethod(operationName = "AddUser", action = "http://tempuri.org/AddUser")
	@WebResult(name = "AddUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AddUser", targetNamespace = "http://tempuri.org/", className = "com.webservice.AddUser")
	@ResponseWrapper(localName = "AddUserResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.AddUserResponse")
	public int addUser(@WebParam(name = "user", targetNamespace = "http://tempuri.org/") WFUser user);

	/**
	 * ���¸����û���Ϣ
	 * 
	 * @param user
	 * @return returns int
	 */
	@WebMethod(operationName = "EditUser", action = "http://tempuri.org/EditUser")
	@WebResult(name = "EditUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditUser", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditUser")
	@ResponseWrapper(localName = "EditUserResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditUserResponse")
	public int editUser(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") WFUser user);

	/**
	 * ��ӻ��û�������Ϣ��IP�б?��ԴȨ�ޣ���ɫ��Ϣ
	 * 
	 * @param settings
	 * @param mappings
	 * @param contracts
	 * @param user
	 * @param hasPerson
	 * @return returns int
	 */
	@WebMethod(operationName = "AddOrganizationUser", action = "http://tempuri.org/AddOrganizationUser")
	@WebResult(name = "AddOrganizationUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AddOrganizationUser", targetNamespace = "http://tempuri.org/", className = "com.webservice.AddOrganizationUser")
	@ResponseWrapper(localName = "AddOrganizationUserResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.AddOrganizationUserResponse")
	public int addOrganizationUser(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") WFUser user,
			@WebParam(name = "contracts", targetNamespace = "http://tempuri.org/") ArrayOfWFContract contracts,
			@WebParam(name = "mappings", targetNamespace = "http://tempuri.org/") ArrayOfAccountIdMapping mappings,
			@WebParam(name = "settings", targetNamespace = "http://tempuri.org/") ArrayOfUserSetting settings,
			@WebParam(name = "hasPerson", targetNamespace = "http://tempuri.org/") boolean hasPerson);

	/**
	 * ���»��û���Ϣ
	 * 
	 * @param user
	 * @param hasPerson
	 * @return returns int
	 */
	@WebMethod(operationName = "EditOrganizationUser", action = "http://tempuri.org/EditOrganizationUser")
	@WebResult(name = "EditOrganizationUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditOrganizationUser", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditOrganizationUser")
	@ResponseWrapper(localName = "EditOrganizationUserResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditOrganizationUserResponse")
	public int editOrganizationUser(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") WFUser user,
			@WebParam(name = "hasPerson", targetNamespace = "http://tempuri.org/") boolean hasPerson);

	/**
	 * ������ԴȨ��
	 * 
	 * @param userId
	 * @param contracts
	 * @return returns int
	 */
	@WebMethod(operationName = "EditContract", action = "http://tempuri.org/EditContract")
	@WebResult(name = "EditContractResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditContract", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditContract")
	@ResponseWrapper(localName = "EditContractResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditContractResponse")
	public int editContract(
			@WebParam(name = "contracts", targetNamespace = "http://tempuri.org/") ArrayOfWFContract contracts,
			@WebParam(name = "userId", targetNamespace = "http://tempuri.org/") String userId);

	/**
	 * ���½�ɫ��ϢAccountIdMapping
	 * 
	 * @param relatedUsers
	 * @param userId
	 * @param mappings
	 * @return returns int
	 */
	@WebMethod(operationName = "EditAccountIdMapping", action = "http://tempuri.org/EditAccountIdMapping")
	@WebResult(name = "EditAccountIdMappingResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditAccountIdMapping", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditAccountIdMapping")
	@ResponseWrapper(localName = "EditAccountIdMappingResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditAccountIdMappingResponse")
	public int editAccountIdMapping(
			@WebParam(name = "mappings", targetNamespace = "http://tempuri.org/") ArrayOfAccountIdMapping mappings,
			@WebParam(name = "relatedUsers", targetNamespace = "http://tempuri.org/") ArrayOfWFUser relatedUsers,
			@WebParam(name = "userId", targetNamespace = "http://tempuri.org/") String userId);

	/**
	 * ���½�ɫ��ϢUserSetting
	 * 
	 * @param userId
	 * @param settings
	 * @return returns int
	 */
	@WebMethod(operationName = "EditUserSetting", action = "http://tempuri.org/EditUserSetting")
	@WebResult(name = "EditUserSettingResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditUserSetting", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditUserSetting")
	@ResponseWrapper(localName = "EditUserSettingResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.EditUserSettingResponse")
	public int editUserSetting(
			@WebParam(name = "settings", targetNamespace = "http://tempuri.org/") ArrayOfUserSetting settings,
			@WebParam(name = "userId", targetNamespace = "http://tempuri.org/") String userId);

}
