package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WFDataCenterInterface service = new WFDataCenterInterface();
 * WFDataCenterInterfaceSoap portType = service.getWFDataCenterInterfaceSoap();
 * portType.helloWorldAsync(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WFDataCenterInterface", targetNamespace = "http://wfdata.sale.gb168.cn/", wsdlLocation = "http://sale.gb168.cn/IdlUserAuth/WFDataCenterInterface.asmx?wsdl")
public class WFDataCenterInterface extends Service {

	private final static URL WFDATACENTERINTERFACE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.webservice.WFDataCenterInterface.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.webservice.WFDataCenterInterface.class.getResource(".");
			url = new URL(baseUrl,
					"http://sale.gb168.cn/IdlUserAuth/WFDataCenterInterface.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://sale.gb168.cn/IdlUserAuth/WFDataCenterInterface.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WFDATACENTERINTERFACE_WSDL_LOCATION = url;
	}

	public WFDataCenterInterface(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WFDataCenterInterface() {
		super(WFDATACENTERINTERFACE_WSDL_LOCATION, new QName("http://wfdata.sale.gb168.cn/",
				"WFDataCenterInterface"));
	}

	/**
	 * 
	 * @return returns WFDataCenterInterfaceSoap
	 */
	@WebEndpoint(name = "WFDataCenterInterfaceSoap")
	public WFDataCenterInterfaceSoap getWFDataCenterInterfaceSoap() {
		return super.getPort(
				new QName("http://wfdata.sale.gb168.cn/", "WFDataCenterInterfaceSoap"),
				WFDataCenterInterfaceSoap.class);
	}

	/**
	 * 
	 * @return returns WFDataCenterInterfaceSoap
	 */
	@WebEndpoint(name = "WFDataCenterInterfaceSoap12")
	public WFDataCenterInterfaceSoap getWFDataCenterInterfaceSoap12() {
		return super.getPort(new QName("http://wfdata.sale.gb168.cn/",
				"WFDataCenterInterfaceSoap12"), WFDataCenterInterfaceSoap.class);
	}

	/**
	 * 
	 * @return returns WFDataCenterInterfaceHttpGet
	 */
	@WebEndpoint(name = "WFDataCenterInterfaceHttpGet")
	public WFDataCenterInterfaceHttpGet getWFDataCenterInterfaceHttpGet() {
		return super.getPort(new QName("http://wfdata.sale.gb168.cn/",
				"WFDataCenterInterfaceHttpGet"), WFDataCenterInterfaceHttpGet.class);
	}

	/**
	 * 
	 * @return returns WFDataCenterInterfaceHttpPost
	 */
	@WebEndpoint(name = "WFDataCenterInterfaceHttpPost")
	public WFDataCenterInterfaceHttpPost getWFDataCenterInterfaceHttpPost() {
		return super.getPort(new QName("http://wfdata.sale.gb168.cn/",
				"WFDataCenterInterfaceHttpPost"), WFDataCenterInterfaceHttpPost.class);
	}

}
